### PR TITLE
adding initial versions of manpages and fixing a typo in README

### PR DESCRIPTION
**Pull request by dogsleg**

### CODE REVIEW

**Comment by mavam** [comment]
A man page is a always a good idea. However, writing manual roff feels a bit tedious. Have you considered Markdown and then generate it with tools such as [md2man](https://github.com/sunaku/md2man)?

**Comment by dogsleg** [comment]
I guess, it depends on what one used to use. I've never used Markdown to write manpages, so in current situation it's better to have something like man2md. ;-)

**Comment by dogsleg** [comment]
So, I've looked at several tools to convert Markdown to groff. As I can see, Markdown is too general thing. That is, when it comes to converting Markdown to groff, there is **no** _one and only_ way. Every project (like [md2man](https://github.com/sunaku/md2man), [ronn](https://rtomayko.github.io/ronn/), or super cool [pandoc](http://pandoc.org/)) invents its own way. It is pretty much like

xkcd's Standards.

**Comment by mavam** [comment]
Well illustrated! :smile:

There are indeed a ton of generators that produce man pages these days. Personally, I've tried ronn and md2man, and also pandoc. Ultimately I settled with md2man as it proved the most flexible in the way [it handles lists](https://github.com/sunaku/md2man/issues/20), although I forgot the exact shortcoming of ronn/pandoc.

In the case of git-notifier, since the README is written in rst, it could make sense to just beef up the README and convert that to a man page?!

**Comment by dogsleg** [comment]
Well, what I've did with manpages is just copy-pasted some contents of README.rst into corresponding sections. And, as you can see, I've separated git-notifier and github-notifier into separate man pages.

I see that you like converting. Do you propose to use a kind of rst2man now? :laughing:

Converting README to Markdown and restructuring it may work, but how would you separate git-notifier and github-notifier man pages in such case? Or so you propose to put everything in just one man page? That would be confusing.

**Comment by mavam** [comment]
Ultimately, we should try to find the solution with the least maintenance effort. That's why I was suggesting a single README-to-man-page conversion script. According to the UNIX philosophy, however, each executable/script should have its own man page; this is what users would expect.

If we had a shell script that would simply chop the README into two pieces and create two man pages, we'd be done. Alternatively, we could also split the README in two pieces and and then invoke the conversion script on both parts. The latter sounds like the least maintenance headaches to me.

Though at this point I'll wait for @rsmmr to chime in, as he's the actual maintainer of the project.

**Comment by rsmmr** [comment]
I agree that it would be nice to have to maintain only one version. But as I don't see that happening soon, and it its nice to have man pages, I've merged it in. Thanks, Lev!

**Comment by sunaku** [comment]
For what it's worth, my approach to solving this problem has been to embed a script's manual page _within_ the script itself, as header comment at the top of the file, and later extract it out (either at compile or run time) using [binman](https://sunaku.github.io/binman), the companion tool for [md2man](https://sunaku.github.io/md2man).  :neckbeard:  This way, the documentation (manual) and the implementation (script) are kept together, in one place, for easy maintenance. :tophat: See [examples here](https://sunaku.github.io/binman/man/man0/README.html#from-the-command-line). :books:

**Pull request merged**
